# Gitee Go CI/CD 配置
# 自动构建 Docker 镜像并推送到镜像仓库

name: Build and Push Docker Image

# 触发条件
on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - master

# 环境变量
env:
  # 镜像仓库配置
  DOCKER_REGISTRY: registry.cn-heyuan.aliyuncs.com
  DOCKER_NAMESPACE: harti123
  IMAGE_NAME: gitea-plugins
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # 1. 检出代码
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      # 2. 设置 Docker Buildx
      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # 3. 登录到 Docker 仓库
      - name: 登录到阿里云容器镜像服务
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # 4. 提取元数据（标签、版本等）
      - name: 提取 Docker 元数据
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_NAMESPACE }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}
      
      # 5. 构建并推送 Docker 镜像
      - name: 构建并推送 Docker 镜像
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.custom
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
      
      # 6. 输出镜像信息
      - name: 输出镜像信息
        run: |
          echo "镜像已构建并推送成功！"
          echo "镜像地址: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_NAMESPACE }}/${{ env.IMAGE_NAME }}"
          echo "标签: ${{ steps.meta.outputs.tags }}"
